site_name: ZuneDev Wiki
site_url: http://zunedev.github.io
repo_url: https://github.com/ZuneDev/Wiki/
edit_uri: blob/main/docs

extra_css:
  - style.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
  - pagetree
  - roamlinks

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js